
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { CustomDatabase } from './dbTypes';

const SUPABASE_URL = "https://ffyzqxplzxcqyceyugzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmeXpxeHBsenhjcXljZXl1Z3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjE3OTEsImV4cCI6MjA1OTkzNzc5MX0.HK7OA1ziudWy9qFYRXFd4uNdwr_7Ps4wL0wUgkjoKY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database & CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
